package view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import java.awt.*;

/**
 * PaymentDialog handles the checkout process.
 * It displays the parking bill and allows the user to choose between Cash or Card.
 */
public class PaymentDialog extends JDialog {
    
    private String selectedMethod = null; // Stores the user's choice: "CASH" or "CARD"

    public PaymentDialog(JFrame parent, String billHtml) {
        // Set up the modal dialog
        super(parent, "Payment Check-out", true); 
        
        setSize(480, 650); 
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());
        getContentPane().setBackground(Color.WHITE);

        // --- 1. Top Header Section ---
        JLabel titleLabel = new JLabel("PARKING CHECK-OUT");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 22));
        titleLabel.setForeground(new Color(52, 152, 219)); // Professional Blue
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setBorder(new EmptyBorder(20, 0, 10, 0));
        
        // --- 2. Middle Bill Content Section ---
        JEditorPane billPane = new JEditorPane();
        billPane.setContentType("text/html");
        billPane.setText(billHtml); // Displays HTML generated by PaymentService
        billPane.setEditable(false);
        billPane.setBackground(new Color(245, 245, 245)); // Light gray background like a receipt
        billPane.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(220, 220, 220), 1),
            new EmptyBorder(10, 10, 10, 10)
        ));
        
        JScrollPane scrollPane = new JScrollPane(billPane);
        scrollPane.setBorder(new EmptyBorder(10, 25, 10, 25)); 
        scrollPane.getViewport().setBackground(Color.WHITE);

        // --- 3. Bottom Action Buttons Section ---
        JPanel btnPanel = new JPanel(new GridLayout(1, 2, 15, 0)); 
        btnPanel.setBorder(new EmptyBorder(20, 25, 25, 25));
        btnPanel.setBackground(Color.WHITE);

        // Cash Payment Button
        JButton cashBtn = createStyledButton("Pay Cash", new Color(46, 204, 113)); 
        cashBtn.addActionListener(e -> {
            selectedMethod = "CASH"; 
            dispose(); // Close dialog
        });

        // Card Payment Button (Triggers the formal card entry form)
        JButton cardBtn = createStyledButton("Pay Card", new Color(52, 152, 219)); 
        cardBtn.addActionListener(e -> {
            performCardSimulation();
        });

        btnPanel.add(cashBtn);
        btnPanel.add(cardBtn);

        add(titleLabel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(btnPanel, BorderLayout.SOUTH);
    }

    /**
     * Simulates a formal Credit/Debit card payment gateway with validation.
     */
    private void performCardSimulation() {
        // Create the card entry form panel
        JPanel cardFormPanel = new JPanel();
        cardFormPanel.setLayout(new BoxLayout(cardFormPanel, BoxLayout.Y_AXIS));
        cardFormPanel.setBackground(Color.WHITE);
        cardFormPanel.setBorder(new EmptyBorder(10, 10, 10, 10));

        JLabel header = new JLabel("Credit or Debit Card Details");
        header.setFont(new Font("Segoe UI", Font.BOLD, 16));
        header.setAlignmentX(Component.LEFT_ALIGNMENT);
        cardFormPanel.add(header);
        cardFormPanel.add(Box.createVerticalStrut(15));

        // Card Number Field
        cardFormPanel.add(createLabel("Card Number"));
        JTextField cardNumField = createTextField("0000 0000 0000 0000");
        cardFormPanel.add(cardNumField);
        cardFormPanel.add(Box.createVerticalStrut(10));

        // Layout for Expiry Date and CVC (Side by side)
        JPanel rowPanel = new JPanel(new GridLayout(1, 2, 15, 0)); 
        rowPanel.setBackground(Color.WHITE);
        rowPanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        // Expiry Date Input
        JPanel expiryPanel = new JPanel(new BorderLayout());
        expiryPanel.setBackground(Color.WHITE);
        expiryPanel.add(createLabel("Expiry Date (MM/YY)"), BorderLayout.NORTH);
        JTextField expiryField = createTextField("MM/YY");
        expiryPanel.add(expiryField, BorderLayout.CENTER);
        
        // CVC Input
        JPanel cvcPanel = new JPanel(new BorderLayout());
        cvcPanel.setBackground(Color.WHITE);
        cvcPanel.add(createLabel("Security Code (CVC)"), BorderLayout.NORTH);
        JTextField cvcField = createTextField("123");
        cvcPanel.add(cvcField, BorderLayout.CENTER);

        rowPanel.add(expiryPanel);
        rowPanel.add(cvcPanel);
        
        JPanel rowContainer = new JPanel(new BorderLayout());
        rowContainer.setBackground(Color.WHITE);
        rowContainer.add(rowPanel, BorderLayout.NORTH);
        rowContainer.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        cardFormPanel.add(rowContainer);
        cardFormPanel.add(Box.createVerticalStrut(20));
        
        // Security Indicator
        JLabel icons = new JLabel("Secured by ParkingPayment Gateway");
        icons.setFont(new Font("Arial", Font.ITALIC, 10));
        icons.setForeground(Color.GRAY);
        icons.setAlignmentX(Component.LEFT_ALIGNMENT);
        cardFormPanel.add(icons);

        // Validation Loop: Keep showing the form until input is valid or user cancels
        while (true) {
            int result = JOptionPane.showConfirmDialog(this, 
                    cardFormPanel, 
                    "Secure Payment Gateway", 
                    JOptionPane.OK_CANCEL_OPTION, 
                    JOptionPane.PLAIN_MESSAGE); 

            if (result != JOptionPane.OK_OPTION) {
                return; // User cancelled the operation
            }

            // --- DATA VALIDATION ---
            String rawCardNum = cardNumField.getText();
            String cardNum = rawCardNum.replaceAll("\\s+", ""); // Strip spaces
            String expiry = expiryField.getText().trim();
            String cvc = cvcField.getText().trim();

            // 1. Validate Card Number (Must be exactly 16 digits)
            if (!cardNum.matches("\\d{16}")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid Card Number!\nPlease enter exactly 16 digits.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                continue; 
            }

            // 2. Validate Expiry Date (Format: MM/YY, Month 01-12)
            if (!expiry.matches("(0[1-9]|1[0-2])/\\d{2}")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid Expiry Date!\nFormat must be MM/YY (e.g., 08/26).", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                continue; 
            }

            // 3. Validate CVC (Must be exactly 3 digits)
            if (!cvc.matches("\\d{3}")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid CVC!\nMust be exactly 3 digits.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                continue; 
            }

            // --- SUCCESS ---
            
            // Show a brief simulated authorization message
            JOptionPane.showMessageDialog(this, 
                "Connecting to Bank Server...\n" +
                "Verifying Card: **** **** **** " + cardNum.substring(12) + "\n\n" +
                "Transaction Authorized!", 
                "Processing Payment", 
                JOptionPane.INFORMATION_MESSAGE);

            selectedMethod = "CARD";
            dispose(); // Close the payment dialog
            break; 
        }
    }

    /**
     * Returns the selected payment method to the caller.
     */
    public String getSelectedMethod() {
        return selectedMethod;
    }

    /**
     * Helper method to create consistent button styles.
     */
    private JButton createStyledButton(String text, Color bg) {
        JButton btn = new JButton(text);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btn.setBackground(bg);
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setPreferredSize(new Dimension(0, 50));
        btn.setBorder(BorderFactory.createEmptyBorder());
        return btn;
    }

    /**
     * Helper method to create styled labels for form fields.
     */
    private JLabel createLabel(String text) {
        JLabel lbl = new JLabel(text);
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lbl.setForeground(new Color(80, 80, 80));
        lbl.setBorder(new EmptyBorder(0, 0, 5, 0));
        return lbl;
    }
    
    /**
     * Helper method to create styled text fields for form input.
     */
    private JTextField createTextField(String placeholder) {
        JTextField tf = new JTextField();
        tf.setFont(new Font("Monospaced", Font.PLAIN, 14));
        tf.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(200, 200, 200), 1, true),
            new EmptyBorder(8, 8, 8, 8)
        ));
        return tf;
    }
}